language: julia
sudo: false
os:
    - linux
addons:
  apt:
    packages:
    - libnlopt0
    - hdf5-tools
julia:
    - 1.0
matrix:
    allow_failures:
notifications:
    email: false
#script: # use the default script setting which is equivalent to the following
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'using Pkg; import QuantEcon; cd(joinpath(dirname(pathof(QuantEcon)))); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - julia -e 'using Pkg; Pkg.add("Documenter")'
    - julia -e 'using Pkg; import QuantEcon; include(joinpath(dirname(pathof(QuantEcon)), "..", "docs", "make.jl"))'
